FLIP
tum-pbs/PhiFlow pull request #26
Opened 2021-01-31 11:20 UTC by PhylomatX

+ Added methods for implementing a FLIP simulation for liquids.
+ Added demo of FLIP simulation
+ Added masked extrapolation method for tensors and for CenteredGrid / StaggeredGrid
+ Added small tests for extrapolation method
+ Added position shift methods to geometries
+ Added runge-kutta advection scheme with velocity-dependent extrapolation
+ Rewrote distribute_points method
+ Changed duplicate_handling in PointCloud sampling method

2021-02-01 16:10 UTC, holl- requested changes
The code is mostly well-documented and well-structured.
However, some function names should be changed to make the code easier to understand.
Also, some functions can be merged into a single function, see attached comments.

2021-02-01 16:10 UTC, holl- commented on phi/physics/flip.py
> +        return PointCloud(v_particle.elements, values=v_values,
```suggestion
        return v_particle.with_(values=v_values)
```

2021-02-01 16:10 UTC, holl- commented on phi/physics/flip.py
> +        # TODO: prefactor of pressure should not have any effect
Does it though?

2021-02-01 16:10 UTC, holl- commented on phi/math/_nd.py
> +def masked_extp(x: Tensor, mask: Tensor, size: int = 1) -> Tuple[Tensor, Tensor]:
```suggestion
def extrapolate_valid(values: Tensor, valid: Tensor, distance_cells: int = 1) -> Tuple[Tensor, Tensor]:
```

2021-02-01 16:10 UTC, holl- commented on phi/geom/_box.py
> +    def shift_positions(self, positions: Tensor, outward: bool = True, shift_amount: float = 0) -> Tensor:
This method needs documentation and the name is not descriptive enough.
How about `repel` or `push`?

Also it seems, this method does not return the new positions but the delta. Wouldn't most applications require the new positions?

2021-02-01 16:10 UTC, holl- commented on phi/field/_grid.py
> +def extp_sgrid(sgrid: StaggeredGrid, mask: StaggeredGrid, size: int = 1) -> Tuple[StaggeredGrid, StaggeredGrid]:
See comment above.

2021-02-02 21:00 UTC, PhylomatX commented
+ Applied all refactorings
+ Merged / Removed some of the methods
+ Implemented new merge method for PointClouds with & operator

2021-02-08 19:23 UTC, merged